import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
const source=(await fs.readFile(new URL('../public/app.js',import.meta.url),'utf8')).replace(/route\(\);\s*$/,'');
function setup(){const classes=new Set(),root={innerHTML:''},content={innerHTML:''},nodes={'#app':root,'#modal':{close(){},showModal(){}},'#modal-content':content,'.sidebar':{classList:{toggle(){}},querySelector(){return {focus(){}}}},'.main':{},'.sidebar-backdrop':{classList:{toggle(){}}}};
  const context=vm.createContext({URL,URLSearchParams,Intl,Date,JSON,Number,String,Response,Error,crypto:{randomUUID:()=> 'key'},location:{href:'http://local/AgendaZap/',hash:''},localStorage:{getItem:()=>null},document:{querySelector:s=>nodes[s]||null,addEventListener(){},body:{classList:{remove:k=>classes.delete(k),toggle(k,v){if(v)classes.add(k);else classes.delete(k);}}}},window:{addEventListener(){}},navigator:{},setTimeout(){},clearTimeout(){},fetch:async()=>json({})});vm.runInContext(source,context);vm.runInContext("session={csrf:'csrf',user:{id:'owner',name:'Owner',role:'owner'},tenant:{id:'tenant',name:'Audit',slug:'audit',timezone:'America/Sao_Paulo'}}",context);return {context,root,classes,content};}
const json=data=>new Response(JSON.stringify(data),{headers:{'content-type':'application/json'}});
test('mobile navigation removes scroll lock',async()=>{const {context,classes}=setup();vm.runInContext('setMobileMenu(true)',context);assert(classes.has('menu-open'));context.location.hash='#login';await vm.runInContext('route()',context);assert(!classes.has('menu-open'));});
test('CRM drops old responses and pending results after navigation',async()=>{
  const {context,root}=setup();let old,newer;context.fetch=url=>new Promise(r=>String(url).includes('q=old')?old=r:newer=r);
  vm.runInContext("pageData.customerQuery='old'",context);const a=vm.runInContext("loadPage('customers')",context);vm.runInContext("pageData.customerQuery='new'",context);const b=vm.runInContext("loadPage('customers')",context);const data={items:[],page:1,pages:1,total:0};newer(json(data));await b;old(json(data));await a;assert(root.innerHTML.includes('value="new"'));
  const pending=vm.runInContext("loadPage('customers')",context);context.location.hash='#login';await vm.runInContext('route()',context);newer(json(data));await pending;assert(root.innerHTML.includes('data-form="login"'));
});
test('401 clears local session and expired-session logout remains reachable',async()=>{const {context}=setup();context.fetch=async()=>new Response('{"error":"Expired"}',{status:401,headers:{'content-type':'application/json'}});context.location.hash='#app/dashboard';await vm.runInContext('route()',context);assert.equal(vm.runInContext('session',context),null);assert.equal(context.location.hash,'login');});
test('manage then back to booking resets incomplete booking state',async()=>{const {context,root}=setup();const catalog={tenant:{slug:'audit',name:'Audit',timezone:'America/Sao_Paulo',cancellation_hours:24},services:[],professionals:[]};context.fetch=async url=>String(url).includes('/manage')?json({catalog,appointment:{id:'a',status:'confirmed',starts_at:'2027-01-01T13:00:00Z',price_cents:0},payment:null}):json(catalog);await vm.runInContext("managePage('a','token')",context);await vm.runInContext("bookingPage('audit')",context);assert.equal(vm.runInContext('bookingState.step',context),1);assert(!root.innerHTML.includes('undefined</div>'));});
test('operator reschedule defaults to the booked professional',async()=>{const {context,content}=setup();vm.runInContext("pageData.appointments=[{id:'a',professional_id:'second'}]",context);context.fetch=async url=>String(url).includes('/services')?json([]):json([{id:'first',name:'First',active:true},{id:'second',name:'Second',active:true}]);await vm.runInContext("action('reschedule',{dataset:{id:'a'}})",context);assert(content.innerHTML.includes('value="second" selected'));});
test('professional dashboard omits unavailable metrics and every role can change password',async()=>{const {context,root}=setup();context.fetch=async()=>json({metrics:{appointments:0},appointments:[]});vm.runInContext("session.user.role='professional'",context);await vm.runInContext("loadPage('dashboard')",context);assert(!root.innerHTML.includes('Receita prevista'));assert(!root.innerHTML.includes('#app/automations'));for(const role of ['professional','attendant']){vm.runInContext(`session.user.role='${role}';shell('dashboard','')`,context);assert(root.innerHTML.includes('data-action="password"'));}});
test('HTML gateway errors are converted into readable messages',async()=>{const {context}=setup();context.fetch=async()=>new Response('<html>502</html>',{status:502,headers:{'content-type':'text/html'}});await assert.rejects(vm.runInContext("api('/dashboard')",context),e=>e.message==='Serviço temporariamente indisponível.');});
test('rendered phone and slug patterns validate their intended inputs',()=>{const {context,root}=setup();vm.runInContext('authPage(true)',context);const slug=root.innerHTML.match(/pattern="([^"]+)"/)[1];const regex=new RegExp('^(?:'+slug+')$','v');assert(regex.test('studio-a'));assert(!regex.test('Studio'));vm.runInContext("bookingState={step:3,catalog:{tenant:{name:'T',cancellation_hours:24,timezone:'UTC'},services:[{id:'s',name:'S',price_cents:0}],professionals:[]},service_id:'s',slot:{starts_at:'2027-01-01T12:00:00Z',professional_name:'P'}};renderBooking()",context);const phone=root.innerHTML.match(/pattern="([^"]+)"/)[1],phoneRegex=new RegExp('^(?:'+phone+')$','v');assert(phoneRegex.test('+5511999999999'));assert(!phoneRegex.test('5511999999999'));});
test('service worker clones before consumption and extends cache-write lifetime',async()=>{
  const handlers={},writes=[],waits=[];let open;const context=vm.createContext({URL,self:{location:{origin:'http://local'},addEventListener:(name,fn)=>handlers[name]=fn},caches:{open:()=>new Promise(r=>open=r)},fetch:async()=>new Response('fresh')});vm.runInContext(await fs.readFile(new URL('../public/sw.js',import.meta.url),'utf8'),context);
  const request={method:'GET',url:'http://local/app.js',mode:'cors'};let response;handlers.fetch({request,respondWith:p=>response=p,waitUntil:p=>waits.push(p)});assert.equal(await (await response).text(),'fresh');open({put:async(key,copy)=>writes.push(await copy.text())});await Promise.all(waits);assert.deepEqual(writes,['fresh']);assert.equal(waits.length,1);
});
