import test from 'node:test';
import assert from 'node:assert/strict';
import * as d from '../src/domain.js';
import {MemoryStore} from '../src/store.js';
import {converse} from '../src/conversation.js';
import {whatsappSignature,pixSignature} from '../src/providers.js';
import {createHmac} from 'node:crypto';

function fixture() {
  const t=d.newTenant({name:'Estúdio teste',slug:'teste'},d.uid());t.min_notice_minutes=0;
  const s={id:d.uid(),name:'Corte',duration_minutes:45,price_cents:8000,deposit_cents:0,active:true};
  const p={id:d.uid(),name:'Ana',active:true,service_ids:[s.id],availability:Array.from({length:7},(_,weekday)=>({weekday,start:'09:00',end:'18:00'}))};t.services.push(s);t.professionals.push(p);
  const date=new Date(Date.now()+3*86400000).toISOString().slice(0,10);
  const input={service_id:s.id,professional_id:p.id,starts_at:d.localToUTC(date,'10:00',t.timezone),name:'Cliente',phone:'+5511999999999',consent:false,idempotency_key:d.uid()};return {t,s,p,date,input};
}
test('timezone converts São Paulo correctly and rejects invalid local times',()=>{assert.equal(d.localToUTC('2026-10-03','09:00','America/Sao_Paulo'),'2026-10-03T12:00:00.000Z');assert.throws(()=>d.localToUTC('2026-03-08','02:30','America/New_York'));});
test('overlap protection applies duration and buffer; adjacent slots remain valid',()=>{const {t,input,date,p,s}=fixture();t.buffer_minutes=15;d.book(t,input);const slots=d.slots(t,s.id,date,p.id);assert(!slots.some(x=>['09:15','09:30','09:45','10:00','10:15','10:30','10:45'].includes(x.time)));assert(slots.some(x=>x.time==='09:00'));assert(slots.some(x=>x.time==='11:00'));assert.throws(()=>d.book(t,{...input,idempotency_key:d.uid()}),/disponível/);});
test('concurrent transactions serialize; exactly one booking persists',async()=>{const {t,input}=fixture();const store=new MemoryStore();store.state.tenants[t.id]=t;const results=await Promise.allSettled(Array.from({length:20},()=>store.transaction('test',state=>d.book(state.tenants[t.id],{...input,idempotency_key:d.uid()}))));assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(store.state.tenants[t.id].appointments.length,1);});
test('idempotency returns original and rejects key reused with different payload',()=>{const{t,input}=fixture();const first=d.book(t,input);assert.equal(d.book(t,input).id,first.id);assert.throws(()=>d.book(t,{...input,name:'Different'}),/reutilizada/);assert.equal(t.appointments.length,1);});
test('blocks, disabled services and professional assignment determine availability',()=>{const {t,input,s,p,date}=fixture();t.blocks.push({professional_id:p.id,starts_at:input.starts_at,ends_at:new Date(Date.parse(input.starts_at)+3600000).toISOString()});assert.throws(()=>d.book(t,input));p.service_ids=[];assert.equal(d.slots(t,s.id,date).length,0);p.service_ids=[s.id];s.active=false;assert.equal(d.slots(t,s.id,date).length,0);});
test('failed transaction does not persist a customer or partial state',async()=>{const {t,input}=fixture();const store=new MemoryStore();store.state.tenants[t.id]=t;await assert.rejects(store.transaction('test',state=>{d.book(state.tenants[t.id],input);throw new Error('Rollback');}));assert.equal(store.state.tenants[t.id].appointments.length,0);assert.equal(store.state.tenants[t.id].customers.length,0);});
test('hold blocks slots, expiry frees them and late paid does not double book',()=>{const {t,input,s}=fixture();s.deposit_cents=2000;const now=Date.now();const a=d.book(t,input,{paymentEnabled:true,now});assert.equal(a.status,'awaiting_payment');assert.throws(()=>d.transition(t,a,'confirmed'),/pagamento/);d.expire(t,now+16*60000);assert.equal(a.status,'expired');const next=d.book(t,{...input,idempotency_key:d.uid()},{paymentEnabled:true,now:now+16*60000});const payment={id:'p1',appointment_id:a.id,amount_cents:2000,status:'pending'};d.settle(t,payment,now+17*60000);assert.equal(a.status,'expired');assert.equal(next.status,'awaiting_payment');assert.equal(payment.needs_review,true);});
test('paid webhook settles once and creates one set of reminders',()=>{const {t,input,s}=fixture();s.deposit_cents=2000;const a=d.book(t,input,{paymentEnabled:true});const payment={id:'p1',appointment_id:a.id,amount_cents:2000,status:'pending'};d.settle(t,payment);const jobs=t.jobs.length;d.settle(t,payment);assert.equal(t.jobs.length,jobs);assert.equal(a.status,'confirmed');assert.equal(a.payment_status,'paid');});
test('reschedule retains identity and releases old slot while replacing reminders',()=>{const {t,input,date,s,p}=fixture();const a=d.book(t,input);d.reschedule(t,a,{starts_at:d.localToUTC(date,'12:00',t.timezone)});assert.equal(a.id,t.appointments[0].id);assert(d.slots(t,s.id,date,p.id).some(x=>x.time==='10:00'));assert(t.jobs.some(j=>j.status==='cancelled'));});
test('completed/no-show terminal state blocks invalid transitions and records visit',()=>{const {t,input}=fixture();const a=d.book(t,input);d.transition(t,a,'completed');assert(d.entity(t,'customers',a.customer_id).last_visit_at);assert.throws(()=>d.transition(t,a,'confirmed'));});
test('WhatsApp deterministic booking and duplicate inbound suppression',()=>{const {t,date}=fixture();const send=text=>converse(t,{phone:'+5511888888888',name:'Maria',text,message_id:d.uid()});send('menu');send('1');send('1');send(date);const reply=send('1');assert.match(reply,/confirmado/);assert.equal(t.appointments.length,1);const key=d.uid();const args={phone:'+5511888888888',name:'Maria',text:'menu',message_id:key};converse(t,args);const length=t.conversations[0].messages.length;assert.equal(converse(t,args),null);assert.equal(t.conversations[0].messages.length,length);});
test('handoff prevents bot competition and opt-out persists consent evidence',()=>{const {t}=fixture();const send=text=>converse(t,{phone:'+5511888888888',name:'Maria',text,message_id:d.uid()});send('humano');assert.equal(send('agendar'),null);send('sair');assert.equal(t.customers[0].consent,false);assert.equal(t.customers[0].consents.at(-1).granted,false);});
test('webhook signatures reject tampering and stale replay',()=>{
  process.env.WHATSAPP_APP_SECRET='test-wa';const body=Buffer.from('{}');const signature='sha256='+createHmac('sha256','test-wa').update(body).digest('hex');assert(whatsappSignature(body,signature));assert(!whatsappSignature(Buffer.from('{"fake":1}'),signature));
  process.env.PIX_WEBHOOK_SECRET='test-pix';const ts=String(Date.now()),requestId='request1',dataId='123';const manifest=`id:123;request-id:request1;ts:${ts};`;const signed=`ts=${ts},v1=${createHmac('sha256','test-pix').update(manifest).digest('hex')}`;assert(pixSignature({signature:signed,requestId,dataId}));assert(!pixSignature({signature:signed,requestId,dataId:'456'}));delete process.env.WHATSAPP_APP_SECRET;delete process.env.PIX_WEBHOOK_SECRET;
});
